{
 "title": "Mikrotik monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"agent_host\""
    }
   },
   {
    "name": "firmware",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"last.firmware\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SHOW TAG VALUES FROM \"mikrotik_db\".\"autogen\".\"snmp\" WITH KEY = \"last.firmware\""
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"sysUpTime\") / (100) AS \"mean_sysUpTime_seconds\"\nFROM \"mikrotik_db\".\"autogen\".\"snmp\"\nWHERE (\"agent_host\"::tag = '${host}')\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "CPU load ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"hrProcessorLoad.1\") + mean(\"hrProcessorLoad.2\") + mean(\"hrProcessorLoad.3\") + mean(\"hrProcessorLoad.4\")) / 4 AS \"mean_cpu_usage_percent\"\nFROM \"mikrotik_db\".\"autogen\".\"snmp\"\nWHERE \"agent_host\" = '${host}'\nGROUP BY time(5m), \"agent_host\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM load ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    mean(\"hrStorageUsed.Memory\") / mean(\"hrStorageSize.Memory\") * 100 AS \"memory_usage_percent\"\nFROM \"mikrotik_db\".\"autogen\".\"snmp\"\nWHERE \"agent_host\"='${host}'\nGROUP BY time(5m), \"agent_host\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"mtxrHlProcessorTemperature\")/10 AS distinct_temperature\nFROM \"autogen\".\"snmp\" \nWHERE (\"agent_host\"::tag = '${host}') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "SELECT\n    mean(\"hrProcessorLoad.1\") AS \"core1\",\n    mean(\"hrProcessorLoad.2\") AS \"core2\",\n    mean(\"hrProcessorLoad.3\") AS \"core3\",\n    mean(\"hrProcessorLoad.4\") AS \"core4\"\nFROM \"mikrotik_db\".\"autogen\".\"snmp\"\nWHERE \"agent_host\" = '${host}'\nGROUP BY time(60s)"
    }
   ]
  },
  {
   "title": "RAM Usage % ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "SELECT\n    mean(\"hrStorageUsed.Memory\") / mean(\"hrStorageSize.Memory\") * 100 AS \"memory_usage_percent\"\nFROM \"mikrotik_db\".\"autogen\".\"snmp\"\nWHERE \"agent_host\"='${host}'\nGROUP BY time(1m), \"agent_host\"\n"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT mean(\"mtxrHlProcessorTemperature\")/10 AS \"mean_mtxrHlProcessorTemperature\"FROM \"mikrotik_db\".\"autogen\".\"snmp\"WHERE \"agent_host\"='${host}' GROUP BY time(5m), \"agent_host\" FILL(0)"
    }
   ]
  }
 ]
}